name: Bitcoin Private
web:
  - 'https://btcprivate.org'
ledgers:
  - id: bitcoin-private
    name: Bitcoin Private
    type: blockchain
    start_date: '2018-03-02'
    forked: true
    networks:
      - id: main
        algorithm: Equihash
        target_block_time: 150
        proof_type: PoW
        tools:
          - type: explorer
            url: 'https://explorer.btcprivate.org/'
assets:
  - id: btcp
    name: Bitcoin Private
    type: native
    ledger: bitcoin-private
    symbol: BTCP
    max_supply: 21000000
    start_date: '2018-01-01'
    webids:
      coinmarketcap: bitcoin-private
      cryptocompare: btcp
      cryptocompare/id: '770095'
clients:
  - id: full-node-desktop-wallet
    name: Full-Node Desktop Wallet
    description: 'Wallet for Bitcoin Private blockchain.'
  - id: electrum-wallet
    name: Electrum Wallet
whitepapers:
  - title: 'Bitcoin Private: Whitepaper'
    file: whitepaper.pdf
tags:
  - fork
webids:
  bitcointalk: '2675257.0'
  github: BTCPrivate
  twitter: bitcoinprivate
  reddit: BTC_Private
  facebook: bitcoinprivate
  youtube/channel: 'UCt5MOeYrCAa-KzjpRSwEwAg'
  instagram: btcprivateofficial
  medium: '@bitcoinprivate'
  discord: 46U2p4m
  telegram: BTCPrivate
  wikipedia/en: Bitcoin_Private
contacts:
  email: 'bitcoinprivateofficial@gmail.com'
