name: Lisk
web:
  - 'https://lisk.io/'
ledgers:
  - id: lisk
    name: Lisk
    type: blockchain
    networks:
      - id: main
        type: main
        algorithm: DPoS
        proof_type: DPoS
        target_block_time: 10
        tools:
          - type: explorer
            url: 'https://explorer.lisk.io/'
          - type: explorer
            url: 'https://explorer.lisk.4miners.net/'
      - id: test
        type: test
        name: Lisk Testnet
        tools:
          - type: explorer
            url: 'https://testnet-explorer.lisk.io/'
assets:
  - id: lsk
    name: Lisk
    type: native
    ledger: lisk
    symbol: LSK
    max_supply: 159918400
    start_date: '2016-05-24'
    first_distribution:
      - title: 'ico'
        percent: 85
      - title: 'team'
        percent: 7.8
      - title: 'advisors'
        percent: 4
      - title: 'supporters'
        percent: 1
      - title: 'first day ico'
        percent: 0.2
    ico_properties:
      start_date: '2016-02-22'
      end_date: '2016-04-21'
      ico_price: 0.0001821238671 BTC
    webids:
      coinmarketcap: lisk
      cryptocompare: lsk
      cryptocompare/id: '19745'
team_url: https://lisk.io/team
team:
  - name: Oliver Beddows
    role: vice president
    webids:
      github: karmacoma
      twitter: Karmacrypto
      linkedin: 'oliver-beddows-19aa09107'
  - name: Mariusz Serek
    role: beckend developer
    webids:
      github: 4miners
      linkedin: 'mariusz-serek'
  - name: Maciej Baj
    role: beckend developer
    webids:
      github: MaciejBaj
      twitter: 'macko_baj'
      linkedin: 'maciej-baj-52a875104'
  - name: Vit Stanislav
    role: frontend developer
    webids:
      github: slaweet
      linkedin: 'v%C3%ADt-stanislav-21b64367'
  - name: Ali Haghighatkhah
    role: frontend developer
    webids:
      github: reyraa
      twitter: 'rey_raa'
      linkedin: 'ali-haghighatkhah-32238784'
webids:
  bitcointalk: '1346646'
  custom/forum: 'https://forum.lisk.io/'
  github: LiskHQ
  twitter: LiskHQ
  reddit: lisk
  gitter: LiskHQ
  facebook: LiskHQ
  instagram: liskhq
  youtube/channel: 'UCuqpGfg_bOQ8Ja4pj811PWg'
  custom/chat: https://lisk.chat/
  telegram: 'Lisk_HQ'
  linkedin/company: lisk
contacts:
  location:hq: 'Zug, Switzerland'
