name: aelf
alt_names:
  - ELF
start_date: '2017-08-13'
description: 'Decentralized Cloud Computing Blockchain Network'
web:
  - 'https://aelf.io/'
assets:
  - id: elf
    start_date: '2017-12-18'
    name: aelf
    type: token
    token_standard: ERC-20
    contract_address: '0xbf2179859fc6d5bee9bf9158632dc51678a4100e'
    decimals: 18
    ledger: ethereum
    symbol: ELF
    max_supply: 1000000000
    ico_properties:
      start_date: '2017-11-28'
      end_date: '2017-12-10'
      total_cap: 300000000
      raised: 24750000 USD
    first_distribution:
      - title: 'public'
        percent: 25
      - title: 'advisors'
        percent: 10
      - title: 'team'
        percent: 16
      - title: 'mining'
        percent: 12
      - title: 'foundation'
        percent: 25
      - title: 'marketing'
        percent: 12
    webids:
      coinmarketcap: aelf
      cryptocompare: elf
      cryptocompare/id: '571314'
webids:
  bitcointalk: '2625637.0'
  bitcoinwiki: Aelf
  custom/forum: 'https://slack.aelf.io/'
  coingecko: aelf
  facebook: aelfofficial
  github: aelfProject
  linkedin/company: aelfblockchain
  medium: aelfblockchain
  twitter: aelfblockchain
  reddit: aelfofficial
  telegram: aelfblockchain
  youtube/channel: aelfblockchain
whitepapers:
  - title: 'Aelf: Decentralized Cloud Computing Blockchain Network'
    url: https://aelf.io/gridcn/AElf.pdf
tags:
  - cloud
  - computing
  - sidechains
  - dpos
  - operatingsystem
team:
  - name: Ma Haobo
    role: CEO, Founder
    photo: https://aelf.io/assets/images/face-1.png
    webids:
      linkedin: haobo-ma-b7b0b251
  - name: Chen Zhuling
    role: Co-Founder, COO
    photo: https://aelf.io/assets/images/face-2.png
    webids:
      linkedin: zhuling-chen-009a6425
  - name: JB Lee
    role: Head of Operations
    photo: https://aelf.io/assets/images/face-12.png
    webids:
      linkedin: jb-lee-98106238
      twitter: thetruejblee
  - name: Peng Rong
    role: CTO
    photo: https://aelf.io/assets/images/face-10.png
    webids:
      twitter: rosonaon
partners:
  - title: 'Alphabit'
    url: https://www.alphabit.fund/
contacts:
  email: 'contact@aelf.io'
  location:hq: 'Singapore, Singapore'
