name: Basic Attention Token
web:
  - 'https://basicattentiontoken.org/'
assets:
  - id: bat
    name: Basic Attention Token
    type: token
    ledger: ethereum
    symbol: BAT
    contract_address: '0x0d8775f648430679a709e98d2b0cb6250d2887ef'
    decimals: 18
    max_supply: 1500000000
    start_date: '2017-05-31'
    webids:
      coinmarketcap: basic-attention-token
      etherscan/token: Bat
      cryptocompare: bat
      cryptocompare/id: '107672'
webids:
  twitter: BAT_Community
  reddit: BATProject
  telegram: batproject
  medium: @attentiontoken
team:
  - name: Brendan Eich
    role: founder
    webids:
      twitter: BrendanEich
  - name: Brian Bondy
    role: co-founder
    webids:
      twitter: brianbondy
  - name: Yan Zhu
    role: security engineering
    webids:
      twitter: bcrypt
  - name: Scott Locklin
    role: smart contracts
contacts:
  email: ifo@basicattentiontoken.org
tags:
  - browser
