name: Waves
alt_names:
  - Waves Platform
web:
  - 'https://wavesplatform.com/'
ledgers:
  - id: waves
    name: Waves
    type: blockchain
    networks:
      - id: main
        type: main
        algorithm: Leased POS
        proof_type: LPoS
        tools:
          - type: explorer
            url: 'http://wavesexplorer.com/'
          - type: explorer
            url: 'http://wavesgo.com/'
      - id: test
        type: test
        tools:
          - type: explorer
            url: 'https://testnet.wavesexplorer.com/'
          - type: faucet
            url: 'https://testnet.wavesexplorer.com/faucet'
assets:
  - id: waves
    name: Waves
    type: native
    ledger: waves
    symbol: WAVES
    max_supply: 100000000
    start_date: '2016-06-12'
    webids:
      coinmarketcap: waves
      cryptocompare: waves
      cryptocompare/id: '20131'
team:
  - name: Alexander Ivanov
    role: founder
    photo: https://en.bitcoinwiki.org/wiki/File:Sacha-waves.jpg
    webids:
      twitter: sasha35625
      linkedin: sasha35625
whitepapers:
  - title: 'Whitepaper'
    file: whitepaper.pdf
webids:
  bitcointalk: '3223136.0'
  custom/forum: 'https://wavestalk.org/'
  telegram: wavesnews
  discord: cnFmDyA
  github: wavesplatform
  twitter: wavesplatform
  reddit: Wavesplatform
  facebook: wavesplatform
  vk: wavesplatform
  custom/blog: 'https://blog.wavesplatform.com/'
  youtube/channel: UCYDQN4Fo4rGnOZ22L5plNIw
  linkedin/company: waves-platform
